{ config, lib, pkgs, ... }:

let
  cfg = config.services.ruyi;

  configToml = lib.generators.toToml { } (
    lib.filterAttrs (_: v: v != { } && v != null) {
      packages = lib.optionalAttrs cfg.settings.packages.prereleases {
        inherit (cfg.settings.packages) prereleases;
      };
      repo = lib.filterAttrs (_: v: v != null && v != "" && v != "main") cfg.settings.repo;
      telemetry = lib.filterAttrs (_: v: v != null && v != "" && v != "local") cfg.settings.telemetry;
    }
  );
in
{
  options.services.ruyi = {
    enable = lib.mkEnableOption "RuyiSDK package manager declarative configuration";

    package = lib.mkPackageOption pkgs "ruyi" { };

    settings = {
      packages.prereleases = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Whether to consider pre-release versions when matching packages.";
      };

      repo = {
        local = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          description = ''
            Local RuyiSDK metadata repository path.
            Must be absolute; ignored if empty or relative.
          '';
        };
        remote = lib.mkOption {
          type = lib.types.str;
          default = "https://github.com/ruyisdk/packages-index.git";
          description = "Remote URL of the RuyiSDK metadata repository.";
        };
        branch = lib.mkOption {
          type = lib.types.str;
          default = "main";
          description = "Branch name to use for the metadata repository.";
        };
      };

      telemetry = {
        mode = lib.mkOption {
          type = lib.types.enum [ "local" "off" "on" ];
          default = "local";
          description = ''
            Telemetry mode.

            - `local`: collect data locally but do not auto-upload (default).
            - `off`: do not collect or upload data.
            - `on`: collect and periodically upload data.
          '';
        };
        upload_consent = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          description = ''
            Timestamp of user consent to upload telemetry.
            Set to current local time to hide the consent banner,
            e.g. `2024-12-02T15:51:00+08:00`.
          '';
        };
        pm_telemetry_url = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          description = "Override the telemetry server URL.";
        };
      };
    };

    telemetryOptout = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Set `RUYI_TELEMETRY_OPTOUT=1` to completely disable telemetry.";
    };

    venv = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Explicitly set the Ruyi virtual environment via `RUYI_VENV`.";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    # System-level configuration file (ruyi searches /etc/ruyi among XDG dirs).
    environment.etc."ruyi/config.toml" = lib.mkIf (configToml != "") {
      text = ''
        # Generated by NixKits services.ruyi — do not edit manually.
        ${configToml}
      '';
    };

    environment.variables = lib.mkMerge [
      (lib.mkIf cfg.telemetryOptout { RUYI_TELEMETRY_OPTOUT = "1"; })
      (lib.mkIf (cfg.venv != null) { RUYI_VENV = cfg.venv; })
    ];
  };
}
