name: Build blender-mcp (x86_64)
on: [push, pull_request]
jobs:
  call:
    uses: ./.github/workflows/build-package.yml
    with:
      package: "blender-mcp"
      runs-on: "ubuntu-latest"
      riscv64-cross: false
    secrets: inherit
