name: Build ruyi-beta (aarch64)
on: [push, pull_request]
jobs:
  call:
    uses: ./.github/workflows/build-package.yml
    with:
      package: "ruyi-beta"
      runs-on: "ubuntu-24.04-arm"
      riscv64-cross: false
    secrets: inherit
