name: Build kitsfmt (riscv64)
on: [push, pull_request]
jobs:
  call:
    uses: ./.github/workflows/build-package.yml
    with:
      package: "kitsfmt"
      runs-on: "ubuntu-latest"
      riscv64-cross: true
    secrets: inherit
