name: Build ruyi (aarch64)
on: [push, pull_request]
jobs:
  call:
    uses: ./.github/workflows/build-package.yml
    with:
      package: "ruyi"
      runs-on: "ubuntu-24.04-arm"
      riscv64-cross: false
    secrets: inherit
