name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: nix flake check --no-write-lock-file
